### ISSUE TITLE
Error configuring API

### ISSUE THREAD

**Issue by cwbffm** [ixxoid/bacula-ce#1]
Hi,

I have this error when trying to configure baculum API

![2022-02-14 11_04_00-Prado_Exceptions_TPhpErrorException - Opera](https://user-images.githubusercontent.com/59570250/153879108-8b026eda-7e66-494a-ac0f-393ad23ce32c.png)

**Comment by ixxoid** [comment]
Hi sorry for the late answer, I had a problem with the e-mail notification..
You need to set the owner for the folder "Baculum_API" and its subfolders and files.
If your docker-compose user is "user" and the users group is "group", then the command would be "chown -R user:group Baculum_API". Then you need to set the file permissions e.g. to: "chmod -R 644 Baculum_API".
You might get similar problems with Baculum_Web or the other containers with incorrect permissions.
Hope this helps
